version: '3'

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - SPARK_MODE=standalone
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_EXPERIMENT_NAME=customer_analysis
      - JAVA_OPTS=-Xmx8g
    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 4g
    depends_on:
      - mlflow

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns 